---
title: 'ESM242 MiniGP: Fisheries -- Model Component'
author: "Emma Tao, Ryan Anderson, Jackson Hayes"
date: "2024-11-17"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Setting Up

```{r}
# Clear Env
rm(list = ls())

# Load Libraries
library(tidyverse)
library(nloptr)
library(knitr)
library(here)

# Set seed for reproducibility
set.seed(1234)
```


## Using Modules

```{r}
# run the module to get the funcitons
source(here("scripts", "fishery_model.R"))
```

## Optimization

```{r}

# Options
local_opts<-list("algorithm"="NLOPT_LN_COBYLA",xtol_rel=1e-15)
options=list("algorithm"="NLOPT_LN_AUGLAG",xtol_rel=1e-15,maxeval=32000,"local_opts"=local_opts)

# Run optimization with best estimates of parameters
SIMULATION_LENGTH <- 24 # Set to 600 eventually, keep it low to test.
INITIAL_STOCK <- 1000
CARRYING_CAPACITY <- 2000
GROWTH_RATE <- 0.1
EFFORT_CAP <- 15
HARVEST_CONSTANT <- 0.05
MIGRATION_CONSTANT <- 0
UTIL_SCALING_CONSTANT <- 1
RHO <- 0.95

# Set seed
set.seed(1224)

result <- nloptr(x0 = c(rep(1, SIMULATION_LENGTH), rep(1, SIMULATION_LENGTH)), eval_f = objective_function, lb = c(rep(0, SIMULATION_LENGTH), rep(0, SIMULATION_LENGTH)), ub = c(rep(EFFORT_CAP, SIMULATION_LENGTH), rep(EFFORT_CAP, SIMULATION_LENGTH)),
                 eval_g_ineq = constraint_function, opts = options, 
                 max_effort = EFFORT_CAP, initial_stock = INITIAL_STOCK, 
                 carrying_capacity = CARRYING_CAPACITY, r = GROWTH_RATE, 
                 q = HARVEST_CONSTANT, z = MIGRATION_CONSTANT, 
                 num_periods = SIMULATION_LENGTH, rho=RHO, util_scaling_constant = UTIL_SCALING_CONSTANT)


# Extract the optimal values
optimal_values <- result$solution
optimal_values



```

## Inspecting Results

Let's see what's going on with the optimal values from the model run. Is it what we expect

```{r}
# Run the model with opimal values
optimal_run <- run_model(optimal_values[1:SIMULATION_LENGTH], optimal_values[(SIMULATION_LENGTH+1):(2*SIMULATION_LENGTH)], EFFORT_CAP, INITIAL_STOCK, CARRYING_CAPACITY, GROWTH_RATE, HARVEST_CONSTANT, MIGRATION_CONSTANT, SIMULATION_LENGTH, RHO, UTIL_SCALING_CONSTANT)
# optimal_run <- run_model(, EFFORT_CAP, INITIAL_STOCK, CARRYING_CAPACITY, GROWTH_RATE, HARVEST_CONSTANT, MIGRATION_CONSTANT, SIMULATION_LENGTH)

# Plot the results

plot(optimal_run$stock1, type = "l", xlab = "Time", ylab = "Stock", main = "Stock 1 Over Time")
plot(optimal_run$stock2, type = "l", xlab = "Time", ylab = "Stock", main = "Stock 2 Over Time")

# plot(optimal_run$harvest_1, type = "l", xlab = "Time", ylab = "Harvest", main = "Harvest 1 Over Time")
# plot(optimal_run$harvest_2, type = "l", xlab = "Time", ylab = "Harvest", main = "Harvest 2 Over Time")

plot(optimal_values[1:SIMULATION_LENGTH], type = "l", xlab = "Time", ylab = "Effort", main = "Effort 1 Over Time")
plot(optimal_values[(SIMULATION_LENGTH+1):(2*SIMULATION_LENGTH)], type = "l", xlab = "Time", ylab = "Effort", main = "Effort 2 Over Time")

# Plot harvest 1 and harvest 2 over time together on one graph
# use ggplot
harvest_data <- data.frame(time = 1:SIMULATION_LENGTH, harvest1 = optimal_run$harvest_1, harvest2 = optimal_run$harvest_2)
harvest_data <- gather(harvest_data, key = "reef", value = "harvest", -time)

ggplot(harvest_data, aes(x = time, y = harvest, color = reef)) + geom_line() + labs(title = "Harvest Over Time", x = "Time", y = "Harvest")


```
